# Generated by Django 5.2.1 on 2025-06-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='date_acceptation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
