# Generated by Django 5.2.1 on 2025-06-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stages', '0002_alter_candidature_date_acceptation'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='date_debut',
            field=models.DateField(blank=True, help_text='Date prévisionnelle de début du stage', null=True, verbose_name='Date de début prévisionnelle'),
        ),
        migrations.AddField(
            model_name='offre',
            name='remuneration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Rémunération mensuelle'),
        ),
        migrations.AddField(
            model_name='offre',
            name='type_stage',
            field=models.CharField(choices=[('plein_temps', 'Plein temps'), ('partiel', 'Partiel'), ('alternance', 'Alternance')], default='plein_temps', max_length=50),
        ),
        migrations.AddField(
            model_name='stage',
            name='nombre_heures',
            field=models.PositiveIntegerField(default=35, verbose_name="Nombre d'heures par semaine"),
        ),
        migrations.AddField(
            model_name='stage',
            name='objectifs',
            field=models.TextField(blank=True, verbose_name='Objectifs du stage'),
        ),
        migrations.AddField(
            model_name='stage',
            name='remuneration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Rémunération mensuelle effective'),
        ),
        migrations.AddField(
            model_name='stage',
            name='tuteur_entreprise_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email du tuteur'),
        ),
        migrations.AddField(
            model_name='stage',
            name='tuteur_entreprise_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone du tuteur'),
        ),
    ]
