# Generated by Django 5.2.3 on 2025-06-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stages', '0003_offre_date_debut_offre_remuneration_offre_type_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
