# Generated by Django 5.2.1 on 2025-06-17 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='candidature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='Stages.candidature'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début prévisionnelle'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='duree_semaines',
            field=models.PositiveIntegerField(help_text='Durée en semaines'),
        ),
    ]
